apiVersion: apps/v1
kind: Deployment
metadata: 
 name: app
spec: 
 replicas: 2
 selector: 
  matchLabels:
   app: dev
 template:
  metadata:
   labels:
    app: dev
  spec:
   containers:
   - name: cont1
     image: nallapareddy/img1:latest
     ports:
      - containerPort: 3000
